# ==============================================================================
#
# FILE:         roles/developer/Brewfile
#
# DESCRIPTION:  This file lists all the Homebrew packages for the 'developer' role.
#
# ==============================================================================

# --- Core Formulae ----------------------------------------------------------

# Node Version Manager
brew "nvm"

# PostgreSQL database
brew "postgresql"

# MariaDB database (MySQL-compatible)
brew "mariadb"

# --- Casks (GUI Applications) -----------------------------------------------

# .NET/C# Development SDK
cask "dotnet-sdk"

# The editor
cask "visual-studio-code"

# iTerm2 for a better terminal experience
cask "iterm2"

# Containerization platform
cask "docker"
