#!/usr/bin/env bash

# ==============================================================================
#
# PHASE:        configure
#
# DESCRIPTION:  Configure git, SSH, and system settings.
#               Sets up user identity and generates SSH keys if needed.
#
# ==============================================================================

# --- Configure Git ---
configure_git() {
  msg_info "Configuring Git..."
  echo ""

  # Check if git user.name is set
  local current_name
  current_name=$(git config --global user.name 2>/dev/null || echo "")

  if [ -z "$current_name" ]; then
    if [ -n "$GIT_USER_NAME" ]; then
      # Use pre-configured name
      git config --global user.name "$GIT_USER_NAME"
      msg_success "Set git user.name: $GIT_USER_NAME"
    else
      # Prompt for name
      msg_info "Git user.name not configured."
      read -rp "Enter your name for Git commits: " input_name
      if [ -n "$input_name" ]; then
        git config --global user.name "$input_name"
        GIT_USER_NAME="$input_name"
        msg_success "Set git user.name: $input_name"
      else
        msg_warning "Git user.name not set. Configure later with: git config --global user.name 'Your Name'"
      fi
    fi
  else
    msg_info "Git user.name already set: $current_name"
  fi

  # Check if git user.email is set
  local current_email
  current_email=$(git config --global user.email 2>/dev/null || echo "")

  if [ -z "$current_email" ]; then
    if [ -n "$GIT_USER_EMAIL" ]; then
      # Use pre-configured email
      git config --global user.email "$GIT_USER_EMAIL"
      msg_success "Set git user.email: $GIT_USER_EMAIL"
    else
      # Prompt for email
      msg_info "Git user.email not configured."
      read -rp "Enter your email for Git commits: " input_email
      if [ -n "$input_email" ]; then
        git config --global user.email "$input_email"
        GIT_USER_EMAIL="$input_email"
        msg_success "Set git user.email: $input_email"
      else
        msg_warning "Git user.email not set. Configure later with: git config --global user.email 'your@email.com'"
      fi
    fi
  else
    msg_info "Git user.email already set: $current_email"
  fi

  # Set recommended Git defaults
  msg_info "Setting recommended Git defaults..."

  # Default branch name
  git config --global init.defaultBranch main 2>/dev/null || true

  # Better diff and merge
  git config --global merge.conflictstyle diff3 2>/dev/null || true
  git config --global diff.colorMoved default 2>/dev/null || true

  # Push behavior
  git config --global push.autoSetupRemote true 2>/dev/null || true

  # Pull behavior
  git config --global pull.rebase false 2>/dev/null || true

  msg_success "Git configuration complete."
}

# --- Configure SSH ---
configure_ssh() {
  msg_info "Configuring SSH..."
  echo ""

  # Check if SSH key exists
  local ssh_key="$HOME/.ssh/id_ed25519"
  local ssh_key_rsa="$HOME/.ssh/id_rsa"

  if [ -f "$ssh_key" ] || [ -f "$ssh_key_rsa" ]; then
    msg_info "SSH key already exists."
    if [ -f "$ssh_key" ]; then
      msg_info "Found: $ssh_key"
    fi
    if [ -f "$ssh_key_rsa" ]; then
      msg_info "Found: $ssh_key_rsa"
    fi
  elif [ "$AUTO_GENERATE_SSH_KEY" = true ]; then
    msg_info "Generating new SSH key..."

    # Determine email for key
    local key_email="${SSH_KEY_EMAIL:-$GIT_USER_EMAIL}"
    if [ -z "$key_email" ]; then
      key_email=$(git config --global user.email 2>/dev/null || echo "")
    fi

    if [ -z "$key_email" ]; then
      msg_warning "No email available for SSH key comment."
      read -rp "Enter email for SSH key (or press Enter to skip): " key_email
    fi

    if [ -n "$key_email" ]; then
      # Create .ssh directory if it doesn't exist
      mkdir -p "$HOME/.ssh"
      chmod 700 "$HOME/.ssh"

      # Generate ED25519 key
      ssh-keygen -t ed25519 -C "$key_email" -f "$ssh_key" -N ""
      msg_success "Generated SSH key: $ssh_key"

      # Start ssh-agent and add key
      eval "$(ssh-agent -s)" >/dev/null 2>&1
      ssh-add "$ssh_key" 2>/dev/null || true

      # Show public key
      echo ""
      msg_info "Your public key (add this to GitHub, GitLab, etc.):"
      echo ""
      cat "${ssh_key}.pub"
      echo ""
    else
      msg_info "Skipping SSH key generation."
      msg_info "Generate later with: fc ssh-keygen"
    fi
  else
    msg_info "SSH key generation disabled in configuration."
    msg_info "Generate manually with: fc ssh-keygen"
  fi

  # Ensure SSH config exists with good defaults
  local ssh_config="$HOME/.ssh/config"
  if [ ! -f "$ssh_config" ]; then
    msg_info "Creating SSH config with recommended settings..."
    mkdir -p "$HOME/.ssh"
    cat > "$ssh_config" << 'EOF'
# SSH Configuration
# Generated by fc bootstrap

# Use macOS keychain for SSH keys
Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ~/.ssh/id_ed25519

# GitHub
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519

# GitLab
Host gitlab.com
    HostName gitlab.com
    User git
    IdentityFile ~/.ssh/id_ed25519
EOF
    chmod 600 "$ssh_config"
    msg_success "Created SSH config: $ssh_config"
  fi

  msg_success "SSH configuration complete."
}

# --- Apply macOS Defaults ---
apply_macos_defaults() {
  msg_info "Applying macOS defaults..."
  echo ""

  # Check if we're on macOS
  if [ "$(uname)" != "Darwin" ]; then
    msg_info "Not on macOS. Skipping macOS defaults."
    return 0
  fi

  # Apply basic sensible defaults
  # These are non-destructive and generally accepted as improvements

  # Finder: show all filename extensions
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true 2>/dev/null || true

  # Finder: show path bar
  defaults write com.apple.finder ShowPathbar -bool true 2>/dev/null || true

  # Finder: show status bar
  defaults write com.apple.finder ShowStatusBar -bool true 2>/dev/null || true

  # Disable the warning when changing a file extension
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false 2>/dev/null || true

  # Avoid creating .DS_Store files on network or USB volumes
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true 2>/dev/null || true
  defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true 2>/dev/null || true

  # Privacy profile specific settings
  case "$BOOTSTRAP_PRIVACY_PROFILE" in
    privacy|lockdown)
      msg_info "Applying enhanced privacy settings..."

      # Disable Siri
      defaults write com.apple.assistant.support "Assistant Enabled" -bool false 2>/dev/null || true

      # Disable personalized ads
      defaults write com.apple.AdLib allowApplePersonalizedAdvertising -bool false 2>/dev/null || true

      if [ "$BOOTSTRAP_PRIVACY_PROFILE" = "lockdown" ]; then
        msg_info "Applying lockdown security settings..."

        # Enable firewall
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on 2>/dev/null || true

        # Enable stealth mode
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on 2>/dev/null || true
      fi
      ;;
  esac

  msg_success "macOS defaults applied."
  msg_info "Some changes may require a logout or restart to take effect."
}

# --- Main Configure Phase ---
msg_info "Starting system configuration..."
echo ""

configure_git
echo ""

configure_ssh
echo ""

apply_macos_defaults
echo ""

msg_success "Configure phase complete."
