# ==============================================================================
#
# FILE:         Brewfile
#
# DESCRIPTION:  This file is the central configuration for Homebrew. It lists
#               all the taps, formulae (command-line tools), casks (GUI apps),
#               and fonts that should be installed.
#
#               Use `brew bundle` to install everything in this file.
#
# ==============================================================================

# --- Taps -------------------------------------------------------------------
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

# --- Formulae (Command-Line Tools) ------------------------------------------
brew "bats-core" # Bash Automated Testing System
brew "blueutil"  # For controlling Bluetooth
brew "git"
brew "mas"       # Mac App Store command-line interface
brew "m-cli"     # Swiss army knife for macOS
brew "node"
brew "redis"
brew "wget"

# --- Casks (GUI & Other Applications) ---------------------------------------
cask "google-chrome"
cask "iterm2"
cask "outset"     # Scripting framework for login/boot actions
cask "visual-studio-code"

# --- Fonts ------------------------------------------------------------------
cask "font-fira-code"
cask "font-hack-nerd-font"
