# ==============================================================================
#
# FILE:         circus.plugin.zsh
#
# DESCRIPTION:  This is the main plugin file for the Dotfiles Flying Circus.
#               It sources all the custom aliases, environment variables, and
#               functions that make up your shell environment.
#
# ==============================================================================

# Get the directory of the current script in a way that is compatible
# with both Zsh and Bash (for testing).
circus_plugin_dir=""
if [ -n "$BASH_VERSION" ]; then
  # We are in Bash
  circus_plugin_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [ -n "$ZSH_VERSION" ]; then
  # We are in Zsh
  circus_plugin_dir="${0:A:h}"
else
  # Fallback for other shells
  circus_plugin_dir=$(dirname "$0")
fi

# Source all alias files.
for alias_file in "$circus_plugin_dir"/aliases/*.sh; do
  source "$alias_file"
done

# Source all environment files.
for env_file in "$circus_plugin_dir"/env/*.sh; do
  source "$env_file"
done

# Source all function files.
for func_file in "$circus_plugin_dir"/functions/*.sh; do
  source "$func_file"
done

# --- Load Role-Specific Configurations --------------------------------------
# Check if a role is defined and load its specific configurations.
local circus_state_dir="$HOME/.circus"
local circus_root_file="$circus_state_dir/root"
local circus_role_file="$circus_state_dir/role"

if [ -f "$circus_root_file" ]; then
  local dotfiles_root
  dotfiles_root=$(cat "$circus_root_file")

  if [ -f "$circus_role_file" ]; then
    local current_role
    current_role=$(cat "$circus_role_file")

    if [ -n "$current_role" ] && [ -d "$dotfiles_root/roles/$current_role" ]; then
      # Source role-specific alias files.
      local role_aliases_dir="$dotfiles_root/roles/$current_role/aliases"
      if [ -d "$role_aliases_dir" ]; then
        for alias_file in "$role_aliases_dir"/*.sh; do
          [ -f "$alias_file" ] && source "$alias_file"
        done
      fi

      # Source role-specific environment files.
      local role_env_dir="$dotfiles_root/roles/$current_role/env"
      if [ -d "$role_env_dir" ]; then
        for env_file in "$role_env_dir"/*.sh; do
          [ -f "$env_file" ] && source "$env_file"
        done
      fi

      # Export role tracking variable
      export FC_ACTIVE_ROLE="$current_role"
    fi
  fi
fi

# --- Load Context-Specific Configurations ------------------------------------
# Source the context environment file if it exists.
# This is generated by `fc context switch` and contains project-specific settings.

local context_env_file="$HOME/.circus/context_env.sh"
if [ -f "$context_env_file" ]; then
  source "$context_env_file"
fi

# Also check for current_context file to set tracking variable
local context_state_file="$HOME/.config/circus/current_context"
if [ -f "$context_state_file" ]; then
  export FC_ACTIVE_CONTEXT="$(cat "$context_state_file")"
fi
