#!/usr/bin/env bash
if [[ "$1" == "services" ]]; then
  echo "redis    started"
elif [[ "$1" == "bundle" && "$2" == "dump" ]]; then
  # Find the file path after --file
  for i in "${!@}"; do
    if [[ ${@:$i:1} == "--file" ]]; then
      file_path=${@:$i+1:1}
      break
    fi
  done
  echo "# This is a dummy Brewfile" > "$file_path"
else
  exit 1
fi
